language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
node_jso:
 - '12'
git:
  depth: 3
script:
  - yarn build
notifications:
  slack: personalproje-dvy7545:WOsknQJ7mr8wW9RuPPw9gBke
  email:
    recipiens:
      - fabiogomez28@gmail.com
    on_success: always
    on_failure: always
    

deploy:
  provider: pages
  skip-cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  target_branch: gh-pages
  commit_message: "Deploy project"
  on:
    branch: master


